spring:
  application:
    name: home-api-gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      server:
        # This is for spring-cloud-starter-gateway-server-webmvc
#        webmvc:
#          routes:
#            - id: home-email-service
#              uri: https://hdash.alok.world
#              predicates:
#                - Path=/email/**
#              filters:
#    #            - StripPrefix=1
#                - PrefixPath=/home
#                - AddResponseHeader=X-Powered-By,Spring Clod Gateway
        # This is for spring-cloud-starter-gateway-server-webflux
        webflux:
          routes:
            - id: home-email-service
              uri: https://hdash.alok.world
              predicates:
                - Path=/email/**
              filters:
                #            - StripPrefix=1
                - PrefixPath=/home
                - AddResponseHeader=X-Powered-By,Spring Clod Gateway for Email Service
                - GlobalCustomFilter

            - id: home-api-service
              uri: https://hdash.alok.world
              predicates:
                - Path=/api/**
              filters:
                #            - StripPrefix=1
                - PrefixPath=/home
                - AddResponseHeader=X-Powered-By,Spring Clod Gateway for API Service
                - GlobalCustomFilter

springdoc:
  api-docs:
    enabled: true
  #    path: /api-docs
  enable-javadoc: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: Home Email Service API
        url: /email/v3/api-docs.yaml

      - name: Home API Service API
        url: /api/v3/api-docs.yaml

debug: true